import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/component/navbar";
import Footer from "@/component/footer";
import { PlanProvider } from "@/context/contextPlan";
import { Toaster } from "react-hot-toast";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html 
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-screen flex flex-col bg-[#090a0d] text-white">
        <PlanProvider>
          <Toaster
            position="top-right"
            toastOptions={{
              style: {
                background: "#12141a",
                color: "#ffffff",
                border: "1px solid #1e232d",
                fontSize: "13px",
                fontWeight: "600",
              },
            }}
          />
        <Navbar />
        {children}
        <Footer />
        </PlanProvider>
        </body>
    </html>
  );
}
